"""Verilator build-reuse proof: identity, recipe gate, and read closure (#1143)."""

from __future__ import annotations

import hashlib
import json
import os
import sys
import time
from dataclasses import replace
from pathlib import Path
from types import SimpleNamespace
from typing import Any, cast

import pytest

from booley.flows.sim import build_reuse
from booley.flows.sim.build_reuse import (
    ReadClosureError,
    VerilatorIdentity,
    build_environment_digest,
    capture_core_closure,
    collect_read_closure,
    parse_depfile,
    stock_verilator_recipe,
    unkeyed_build_environment,
    verify_read_closure,
    verilator_identity,
)
from booley.flows.sim.build_session import (
    SimulationBuildSession,
    SimulationBuildSlotError,
    _generation_neutral,
    _verilator_reuse_key,
)
from booley.targets.domain import TargetHandle

posix_only = pytest.mark.skipif(
    os.name == "nt", reason="Verilator reuse runs in the Linux Sandbox"
)


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _identity(root: Path, include: Path | None = None) -> VerilatorIdentity:
    verilator_root = root / "vroot"
    (verilator_root / "include").mkdir(parents=True, exist_ok=True)
    verilated_mk = verilator_root / "include" / "verilated.mk"
    if not verilated_mk.exists():
        verilated_mk.write_text("CXX = g++\nLINK = g++\n", encoding="utf-8")
    dirs = (include.resolve(),) if include is not None else ()
    return VerilatorIdentity("tool", verilator_root.resolve(), dirs)


# --------------------------------------------------------------------------
# Dependency files
# --------------------------------------------------------------------------


def test_depfile_parser_handles_continuations_escapes_and_phony_rules() -> None:
    text = (
        "Vtop.o: Vtop.cpp Vtop.h \\\n"
        "  /opt/v/include/verilated.h my\\ dir/a.h cost$$.h\n"
        "\n"
        "Vtop.h:\n"
        "/opt/v/include/verilated.h:\n"
    )
    assert parse_depfile(text) == [
        "Vtop.cpp",
        "Vtop.h",
        "/opt/v/include/verilated.h",
        "my dir/a.h",
        "cost$.h",
    ]


def test_depfile_parser_rejects_non_rule_lines() -> None:
    with pytest.raises(ReadClosureError, match="malformed"):
        parse_depfile("not a rule at all\n")


# --------------------------------------------------------------------------
# Recipe gate
# --------------------------------------------------------------------------


def _stock_recipe(build_root: Path, vc: str, *, make_options: str = "-j4") -> None:
    """Write what the Edalize flow API generates for one Verilator Target."""
    build_root.mkdir(parents=True, exist_ok=True)
    (build_root / "Makefile").write_text(
        "#Auto generated by Edalize\n\n"
        "all: post_build\n\n"
        "pre_build: \n\n"
        "Vtop.mk: demo.vc src/top.sv | pre_build\n"
        "\t$(EDALIZE_LAUNCHER) verilator -f demo.vc\n\n"
        "Vtop: Vtop.mk src/dpi.cpp | pre_build\n"
        f"\t$(EDALIZE_LAUNCHER) make -f Vtop.mk {make_options}\n\n"
        "post_build: Vtop\n\n"
        "pre_run: \n\n"
        "run: pre_run\n\n"
        "post_run: run\n",
        encoding="utf-8",
    )
    (build_root / "demo.vc").write_text(vc, encoding="utf-8")
    (build_root / "src" / "inc").mkdir(parents=True, exist_ok=True)


_CONTAINED_VC = (
    "--Mdir .\n--cc\n+incdir+src/inc\n-CFLAGS -Isrc/inc\nsrc/top.sv\n--top-module top\n--exe\n"
)


@pytest.mark.parametrize(
    ("vc", "make_options"),
    [
        (_CONTAINED_VC, "-j8 VM_PARALLEL_BUILDS=1"),
        (_CONTAINED_VC + "--trace\n-LDFLAGS -lpthread\n", "OPT_FAST=-O2"),
        (_CONTAINED_VC, ""),
        (_CONTAINED_VC + "lib/libdpi.a\n", ""),
    ],
)
def test_stock_recipe_with_contained_search_dirs_is_supported(
    tmp_path: Path, vc: str, make_options: str
) -> None:
    _stock_recipe(tmp_path / "b", vc, make_options=make_options)
    assert stock_verilator_recipe(tmp_path / "b") is not None


@pytest.mark.parametrize(
    ("vc", "make_options"),
    [
        (_CONTAINED_VC + "+incdir+../../outside\n", ""),
        (_CONTAINED_VC + "+incdir+/usr/share\n", ""),
        (_CONTAINED_VC + "-CFLAGS -I/opt/include\n", ""),
        (_CONTAINED_VC + '-CFLAGS "-isystem /opt/include"\n', ""),
        (_CONTAINED_VC + "-LDFLAGS /opt/lib/libdpi.a\n", ""),
        (_CONTAINED_VC + "/opt/lib/libdpi.so\n", ""),
        (_CONTAINED_VC + "../outside/libdpi.a\n", ""),
        (_CONTAINED_VC + '-LDFLAGS "-L/opt/lib -ldpi"\n', ""),
        (_CONTAINED_VC + "-f other.vc\n", ""),
        (_CONTAINED_VC + "-y /opt/rtl\n", ""),
        (_CONTAINED_VC, "CXX=clang++"),
        (_CONTAINED_VC, "-e"),
        (_CONTAINED_VC, "--eval=CXX:=clang++"),
    ],
)
def test_recipe_gate_declines_uncontained_search_and_toolchain_overrides(
    tmp_path: Path, vc: str, make_options: str
) -> None:
    _stock_recipe(tmp_path / "b", vc, make_options=make_options)
    assert stock_verilator_recipe(tmp_path / "b") is None


def test_recipe_reports_libraries_the_linker_finds_outside_the_generation(
    tmp_path: Path,
) -> None:
    build = tmp_path / "b"
    _stock_recipe(build, _CONTAINED_VC + '-LDFLAGS "-Llib -lstaged -lz -l m -l:libspecial.so.1"\n')
    (build / "lib").mkdir()
    (build / "lib" / "libstaged.a").write_bytes(b"!<arch>\n")
    recipe = stock_verilator_recipe(build)
    assert recipe is not None
    # ``libstaged`` is a staged input; the others resolve on the system path.
    assert recipe.system_libraries == (
        ("libz.so", "libz.a"),
        ("libm.so", "libm.a"),
        ("libspecial.so.1",),
    )


@pytest.mark.parametrize(
    "change",
    [
        lambda text: text.replace("pre_build: \n", "pre_build: \n\tpython3 gen.py\n"),
        lambda text: text + "\nextra:\n\ttouch pwned\n",
        lambda text: "CXX := clang++\n" + text,
        lambda text: text.replace("verilator -f demo.vc", "verilator -f demo.vc --build"),
        lambda text: text.replace("make -f Vtop.mk", "make -f Other.mk"),
        lambda text: text.replace("\t$(EDALIZE_LAUNCHER) verilator -f demo.vc\n", ""),
        lambda text: "",
    ],
)
def test_recipe_gate_declines_non_stock_makefiles(tmp_path: Path, change: Any) -> None:
    build_root = tmp_path / "b"
    _stock_recipe(build_root, _CONTAINED_VC)
    makefile = build_root / "Makefile"
    makefile.write_text(change(makefile.read_text(encoding="utf-8")), encoding="utf-8")
    assert stock_verilator_recipe(build_root) is None


# --------------------------------------------------------------------------
# Core closure
# --------------------------------------------------------------------------


def _edam(work: Path, cores: dict[str, Path]) -> Path:
    work.mkdir(parents=True, exist_ok=True)
    edam = work / "demo.eda.yml"
    edam.write_text(
        json.dumps(
            {
                "cores": {
                    name: {"core_file": os.path.relpath(path, work), "dependencies": []}
                    for name, path in cores.items()
                }
            }
        ),
        encoding="utf-8",
    )
    return edam


def test_core_closure_hashes_every_dependency_core(tmp_path: Path) -> None:
    project = tmp_path / "project"
    (project / "rtl").mkdir(parents=True)
    adapter = project / "adapter.core"
    rtl = project / "rtl" / "rtl.core"
    adapter.write_text("CAPI=2:\nname: a:b:adapter:1\n", encoding="utf-8")
    rtl.write_text("CAPI=2:\nname: a:b:rtl:1\n", encoding="utf-8")
    edam = _edam(project / ".booley_project" / "g", {"a:b:adapter:1": adapter, "a:b:rtl:1": rtl})

    closure = capture_core_closure(edam, project)

    assert closure == {
        "a:b:adapter:1": f"adapter.core:{_sha(adapter)}",
        "a:b:rtl:1": f"rtl/rtl.core:{_sha(rtl)}",
    }
    rtl.write_text("CAPI=2:\nname: a:b:rtl:1\ndescription: edited\n", encoding="utf-8")
    assert capture_core_closure(edam, project) != closure


@pytest.mark.parametrize("case", ["generator", "outside", "missing", "no-cores", "malformed-edam"])
def test_core_closure_declines_unprovable_cores(tmp_path: Path, case: str) -> None:
    project = tmp_path / "project"
    project.mkdir()
    core = project / "demo.core"
    core.write_text("CAPI=2:\nname: a:b:demo:1\n", encoding="utf-8")
    if case == "generator":
        core.write_text("CAPI=2:\nname: a:b:demo:1\ngenerate: {g: {generator: x}}\n")
    elif case == "outside":
        core = tmp_path / "elsewhere.core"
        core.write_text("CAPI=2:\nname: a:b:demo:1\n", encoding="utf-8")
    elif case == "missing":
        core = project / "gone.core"
    edam = _edam(project / "g", {} if case == "no-cores" else {"a:b:demo:1": core})
    if case == "malformed-edam":
        edam.write_text(": not yaml : [", encoding="utf-8")
    assert capture_core_closure(edam, project) is None


# --------------------------------------------------------------------------
# Read closure
# --------------------------------------------------------------------------


def _fresh_build(tmp_path: Path) -> tuple[Path, Path, Path, VerilatorIdentity]:
    """A generation whose depfiles name staged, generated, and toolchain files."""
    project = tmp_path / "project"
    work = project / ".booley_project" / "g" / "0123456789abcdef"
    build = work
    (build / "src").mkdir(parents=True)
    identity = _identity(tmp_path)
    header = identity.verilator_root / "include" / "verilated.h"
    header.write_text("// verilated\n", encoding="utf-8")
    verilator_bin = identity.verilator_root / "bin" / "verilator_bin"
    verilator_bin.parent.mkdir(parents=True, exist_ok=True)
    verilator_bin.write_text("binary", encoding="utf-8")
    (build / "src" / "top.sv").write_text("module top; endmodule\n", encoding="utf-8")
    (build / "src" / "defs.svh").write_text("`define X 1\n", encoding="utf-8")
    (build / "Vtop.cpp").write_text("// generated\n", encoding="utf-8")
    (build / "dpi.cpp").write_text("// dpi\n", encoding="utf-8")
    (build / "Vtop__ver.d").write_text(
        f"Vtop.cpp Vtop.h : {verilator_bin} src/top.sv src/defs.svh\n", encoding="utf-8"
    )
    for stem, source in (("Vtop", "Vtop.cpp"), ("dpi", "dpi.cpp")):
        (build / f"{stem}.o").write_bytes(b"object")
        (build / f"{stem}.d").write_text(f"{stem}.o: {source} {header}\n", encoding="utf-8")
    return project, work, build, identity


def _settled_capture_ns() -> int:
    """A capture time safely after every fixture file's inode change."""
    return time.time_ns() + 10 * build_reuse.RACE_MARGIN_NS


def test_read_closure_classifies_generation_and_toolchain_files(tmp_path: Path) -> None:
    project, work, build, identity = _fresh_build(tmp_path)

    closure = collect_read_closure(build, work, identity, project, _settled_capture_ns())

    root = identity.verilator_root
    assert set(closure) == {
        "work:src/top.sv",
        "work:src/defs.svh",
        "work:Vtop.cpp",
        "work:dpi.cpp",
        f"abs:{root / 'bin' / 'verilator_bin'}",
        f"abs:{root / 'include' / 'verilated.h'}",
    }
    assert closure["work:src/defs.svh"] == _sha(build / "src" / "defs.svh")
    assert verify_read_closure(closure, work, identity, project)


@pytest.mark.parametrize(
    ("victim", "change"),
    [
        ("src/defs.svh", "included header"),
        ("dpi.cpp", "DPI source"),
        ("vroot/include/verilated.h", "toolchain header"),
    ],
)
def test_read_closure_detects_any_changed_file(tmp_path: Path, victim: str, change: str) -> None:
    project, work, build, identity = _fresh_build(tmp_path)
    closure = collect_read_closure(build, work, identity, project, _settled_capture_ns())
    path = tmp_path / victim if victim.startswith("vroot") else build / victim
    path.write_text(f"// {change} edited\n", encoding="utf-8")
    assert not verify_read_closure(closure, work, identity, project)


@pytest.mark.parametrize("case", ["missing-d", "two-ver-d", "no-objects", "outside", "race"])
def test_read_closure_refuses_incomplete_or_unsafe_evidence(tmp_path: Path, case: str) -> None:
    project, work, build, identity = _fresh_build(tmp_path)
    captured = _settled_capture_ns()
    if case == "missing-d":
        (build / "dpi.d").unlink()
    elif case == "two-ver-d":
        (build / "Valt__ver.d").write_text("Valt.cpp : src/top.sv\n", encoding="utf-8")
    elif case == "no-objects":
        for path in build.glob("*.o"):
            path.unlink()
    elif case == "outside":
        stray = tmp_path / "stray.h"
        stray.write_text("// outside every allowed root\n", encoding="utf-8")
        (build / "dpi.d").write_text(f"dpi.o: dpi.cpp {stray}\n", encoding="utf-8")
    else:
        captured = time.time_ns()  # toolchain header changed "during" the build
    with pytest.raises(ReadClosureError):
        collect_read_closure(build, work, identity, project, captured)


@pytest.mark.parametrize(
    "tamper",
    ["escape", "outside-abs", "relative-abs", "unknown-kind", "empty", "not-a-dict", "symlink"],
)
def test_read_closure_verification_rejects_hostile_manifests(tmp_path: Path, tamper: str) -> None:
    project, work, build, identity = _fresh_build(tmp_path)
    closure: Any = collect_read_closure(build, work, identity, project, _settled_capture_ns())
    secret = tmp_path / "secret"
    secret.write_text("secret", encoding="utf-8")
    if tamper == "escape":
        closure["work:../../../../secret"] = _sha(secret)
    elif tamper == "outside-abs":
        closure[f"abs:{secret}"] = _sha(secret)
    elif tamper == "relative-abs":
        closure["abs:secret"] = _sha(secret)
    elif tamper == "unknown-kind":
        closure["file:secret"] = _sha(secret)
    elif tamper == "empty":
        closure = {}
    elif tamper == "not-a-dict":
        closure = list(closure)
    else:
        target = build / "src" / "top.sv"
        moved = build / "top.real"
        target.rename(moved)
        target.symlink_to(moved)
    assert not verify_read_closure(closure, work, identity, project)


# --------------------------------------------------------------------------
# Environment and toolchain identity
# --------------------------------------------------------------------------


def test_environment_digest_tracks_only_build_relevant_names(tmp_path: Path) -> None:
    build = tmp_path / "b"
    _stock_recipe(build, _CONTAINED_VC)
    identity = _identity(tmp_path)
    (identity.verilator_root / "include" / "verilated.mk").write_text(
        "CXX = g++\nLINK = g++\nCPPFLAGS += $(EXTRA_FROM_VERILATED_MK)\n", encoding="utf-8"
    )
    base = {"PATH": "/usr/bin", "HOME": "/home/a", "TERM": "xterm"}
    digest = build_environment_digest(base, build, identity)

    unrelated = {**base, "HOME": "/home/b", "TERM": "dumb", "SHLVL": "3", "CCACHE_DIR": "/c"}
    assert build_environment_digest(unrelated, build, identity) == digest
    for name, value in (
        ("CXXFLAGS", "-O0"),
        ("PATH", "/opt/bin:/usr/bin"),
        ("EXTRA_FROM_VERILATED_MK", "-DX"),
        ("VERILATOR_ROOT", "/opt/v"),
        ("VM_PARALLEL_BUILDS", "0"),
        ("EDALIZE_LAUNCHER", "valgrind"),
    ):
        assert build_environment_digest({**base, name: value}, build, identity) != digest, name


def test_environment_digest_covers_installation_makefiles_and_generated_families(
    tmp_path: Path,
) -> None:
    build = tmp_path / "b"
    _stock_recipe(build, _CONTAINED_VC)
    identity = _identity(tmp_path)
    (identity.verilator_root / "include" / "verilated_extra.mk").write_text(
        "CPPFLAGS += $(FROM_INCLUDED_MK)\n", encoding="utf-8"
    )
    base = {"PATH": "/usr/bin"}
    digest = build_environment_digest(base, build, identity)
    # Names the makefiles Verilator generates read, plus Make's own inputs.
    for name in (
        "FROM_INCLUDED_MK",
        "LIBS",
        "LOADLIBES",
        "SC_LIBS",
        "VK_USER_OBJS",
        "VPATH",
        "MAKEFILES",
    ):
        assert build_environment_digest({**base, name: "x"}, build, identity) != digest, name


def test_generated_makefiles_reading_unkeyed_environment_are_reported(tmp_path: Path) -> None:
    build = tmp_path / "b"
    _stock_recipe(build, _CONTAINED_VC)
    identity = _identity(tmp_path)
    (build / "Vtop.mk").write_text(
        "CXXFLAGS += $(MY_FLAGS)\nLIBS += $(VK_USER_OBJS)\nSTRANGE ?= 1\n", encoding="utf-8"
    )
    environment = {"MY_FLAGS": "-O0", "VK_USER_OBJS": "a.o", "STRANGE": "2", "OTHER": "x"}
    assert unkeyed_build_environment(build, identity, environment) == ["MY_FLAGS", "STRANGE"]
    assert unkeyed_build_environment(build, identity, {"OTHER": "x"}) == []


def _fake_install(tmp_path: Path) -> tuple[Path, dict[str, str]]:
    """A Verilator wrapper, install tree, and scripted C++ driver."""
    root = tmp_path / "vroot"
    bin_dir = tmp_path / "bin"
    include = tmp_path / "sysinclude"
    for path in (root / "bin", root / "include", bin_dir, include / "bits"):
        path.mkdir(parents=True)
    (include / "stdio.h").write_text("// libc\n", encoding="utf-8")
    (root / "include" / "verilated.mk").write_text(
        "CXX = fakecxx\nLINK = fakecxx\nAR = ar\n", encoding="utf-8"
    )
    (root / "include" / "verilated.h").write_text("// v\n", encoding="utf-8")
    (root / "bin" / "verilator_bin").write_text("bin\n", encoding="utf-8")
    scripts = {
        "verilator": f"print({str(root)!r})\n",
        "fakecxx": (
            "import sys\n"
            "args = sys.argv[1:]\n"
            "if args and args[0].startswith('-print-prog-name='):\n"
            "    print(sys.argv[0])\n"
            "elif args and args[0].startswith('-print-file-name='):\n"
            "    import os\n"
            "    name = args[0].split('=', 1)[1]\n"
            f"    found = os.path.join({str(tmp_path / 'syslib')!r}, name)\n"
            "    print(found if os.path.isfile(found) else name)\n"
            "elif '-E' in args:\n"
            "    sys.stderr.write('#include <...> search starts here:\\n "
            f"{include}\\nEnd of search list.\\n')\n"
            "else:\n"
            "    print('fakecxx 1.0 ' + ' '.join(args))\n"
        ),
    }
    for name, body in scripts.items():
        script = bin_dir / name
        script.write_text(f"#!{sys.executable}\n{body}", encoding="utf-8")
        script.chmod(0o755)
    return root, {"PATH": f"{bin_dir}{os.pathsep}{os.environ['PATH']}"}


@posix_only
def test_toolchain_identity_covers_install_compiler_and_system_headers(tmp_path: Path) -> None:
    root, environment = _fake_install(tmp_path)
    identity = verilator_identity(environment)
    assert identity is not None
    assert identity.verilator_root == root.resolve()
    assert identity.system_include_dirs == ((tmp_path / "sysinclude").resolve(),)
    assert verilator_identity(environment) == identity

    # Only the compiler drivers are mandatory, but any named tool must resolve.
    mk = root / "include" / "verilated.mk"
    mk.write_text("CXX = fakecxx\nLINK = fakecxx\n", encoding="utf-8")
    assert verilator_identity(environment) is not None
    mk.write_text("CXX = fakecxx\nLINK = fakecxx\nAR = no-such-ar\n", encoding="utf-8")
    assert verilator_identity(environment) is None
    mk.write_text("CXX = fakecxx\nLINK = fakecxx\n", encoding="utf-8")

    for change in (
        lambda: (root / "include" / "verilated.h").write_text("// v2\n", encoding="utf-8"),
        lambda: (tmp_path / "sysinclude" / "bits" / "new.h").write_text("", encoding="utf-8"),
        lambda: (tmp_path / "bin" / "fakecxx").write_text(
            (tmp_path / "bin" / "fakecxx").read_text(encoding="utf-8") + "# v2\n",
            encoding="utf-8",
        ),
    ):
        before = verilator_identity(environment)
        change()
        after = verilator_identity(environment)
        assert before is not None and after is not None
        assert after.digest != before.digest


@posix_only
def test_toolchain_identity_hashes_linked_system_libraries(tmp_path: Path) -> None:
    _root, environment = _fake_install(tmp_path)
    syslib = tmp_path / "syslib"
    syslib.mkdir()
    (syslib / "libz.a").write_bytes(b"archive v1")
    libz = (("libz.so", "libz.a"),)
    before = verilator_identity(environment, libz)
    assert before is not None
    assert (syslib / "libz.a").resolve() in before.tool_files
    assert verilator_identity(environment) != before
    (syslib / "libz.a").write_bytes(b"archive v2")
    after = verilator_identity(environment, libz)
    assert after is not None and after.digest != before.digest
    # A library the linker cannot be shown to find is never guessed at.
    assert verilator_identity(environment, (("libnone.so", "libnone.a"),)) is None


@posix_only
def test_toolchain_identity_declines_without_compiler_or_installation(tmp_path: Path) -> None:
    root, environment = _fake_install(tmp_path)
    (root / "include" / "verilated.mk").write_text("AR = ar\n", encoding="utf-8")
    assert verilator_identity(environment) is None
    assert verilator_identity({"PATH": str(tmp_path / "empty")}) is None


# --------------------------------------------------------------------------
# Session integration
# --------------------------------------------------------------------------


def _handle(root: Path) -> TargetHandle:
    (root / ".booley_project").mkdir(exist_ok=True)
    return cast(TargetHandle, SimpleNamespace(project_root=root, identity="acme:lib:demo:1#sim"))


def test_generation_path_never_reaches_the_target_environment_key(tmp_path: Path) -> None:
    build = tmp_path / "g" / "aaaa"
    prepared = cast(
        Any,
        SimpleNamespace(
            build_root=build,
            environment={
                "CCACHE_BASEDIR": str(build.absolute()),
                "USER_CPPFLAGS": f"-fdebug-prefix-map={build.absolute()}=.",
                "PLAIN": "1",
            },
        ),
    )
    assert _generation_neutral(prepared) == {
        "CCACHE_BASEDIR": "<generation>",
        "USER_CPPFLAGS": "-fdebug-prefix-map=<generation>=.",
        "PLAIN": "1",
    }


@pytest.mark.parametrize(
    ("environment", "cocotb", "closure"),
    [
        ({"BOOLEY_INTERNAL_SELFTEST_KIND": "bad"}, "", {"c": "d"}),
        ({}, "tests.test_top", {"c": "d"}),
        ({}, "", None),
        ({"EDALIZE_LAUNCHER": "valgrind"}, "", {"c": "d"}),
        ({"MAKEFLAGS": "-j2"}, "", {"c": "d"}),
    ],
    ids=["doctor-bad", "cocotb", "unproven-cores", "launcher", "makeflags"],
)
def test_verilator_key_declines_ineligible_builds(
    monkeypatch: pytest.MonkeyPatch,
    environment: dict[str, str],
    cocotb: str,
    closure: dict[str, str] | None,
) -> None:
    monkeypatch.setattr(build_reuse, "verilator_identity", lambda *_args: pytest.fail("probed"))
    prepared = cast(
        Any,
        SimpleNamespace(resolved=SimpleNamespace(cocotb_module=cocotb), core_closure=closure),
    )
    assert _verilator_reuse_key(prepared, {}, environment) is None


def _keyed_generation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, session: SimulationBuildSession
) -> tuple[Any, dict[str, str]]:
    """A leased Verilator generation whose key and identity are pinned."""
    work = session.new_generation()
    (work / "src").mkdir()
    source = work / "src" / "top.sv"
    source.write_text("module top; endmodule\n", encoding="utf-8")
    (work / "Vtop").write_text("#!/bin/sh\n", encoding="utf-8")
    (work / "Vtop").chmod(0o755)
    (work / "Vtop__ver.d").write_text("Vtop.cpp : src/top.sv\n", encoding="utf-8")
    (work / "Vtop.cpp").write_text("// generated\n", encoding="utf-8")
    (work / "Vtop.o").write_bytes(b"o")
    (work / "Vtop.d").write_text("Vtop.o: Vtop.cpp\n", encoding="utf-8")
    (work / "Makefile").write_text("# stock recipe (key pinned below)\n", encoding="utf-8")
    identity = _identity(tmp_path)
    monkeypatch.setattr(
        "booley.flows.sim.build_session._verilator_reuse_key",
        lambda *_args: ("key", identity),
    )
    prepared = SimpleNamespace(
        work_root=work,
        build_root=work,
        eda_tool="verilator",
        target_identity=session.handle.identity,
        toplevel="top",
        resolved=SimpleNamespace(cocotb_module=""),
        environment={},
    )
    inputs = {"src/top.sv": _sha(source)}
    return prepared, inputs


def _manifest(prepared: Any) -> dict[str, Any]:
    return json.loads((prepared.build_root / ".booley-build-manifest.json").read_text("utf-8"))


@posix_only
def test_keyed_verilator_image_records_its_read_closure_and_promotes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    session = SimulationBuildSession(_handle(tmp_path))
    with session:
        prepared, inputs = _keyed_generation(tmp_path, monkeypatch, session)
        captured = session.capture_inputs(prepared)
        session._captured_ns[prepared.work_root] = _settled_capture_ns()
        key = session.reusable_key(prepared, captured, hooks=False)
        session.authorize_fresh_image(prepared, inputs, key)

        manifest = _manifest(prepared)
        assert manifest["reusable"] is True
        assert set(manifest["read_closure"]) == {"work:src/top.sv", "work:Vtop.cpp"}
        assert (session.slot / "current.json").is_file()
        session.verify_image(prepared)
        manifest_path = prepared.build_root / ".booley-build-manifest.json"
        manifest_path.write_text(json.dumps({**manifest, "input_key": None}), encoding="utf-8")
        with pytest.raises(SimulationBuildSlotError, match="identity changed"):
            session.verify_image(prepared)
        manifest_path.write_text(json.dumps(manifest), encoding="utf-8")

        assert session._read_closure_matches(prepared.work_root, manifest, prepared)
        (prepared.work_root / "Vtop.cpp").write_text("// tampered\n", encoding="utf-8")
        assert not session._read_closure_matches(prepared.work_root, manifest, prepared)


@posix_only
def test_unprovable_read_closure_downgrades_without_failing_the_build(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    session = SimulationBuildSession(_handle(tmp_path))
    with session:
        prepared, inputs = _keyed_generation(tmp_path, monkeypatch, session)
        (prepared.build_root / "Vtop.d").unlink()
        captured = session.capture_inputs(prepared)
        key = session.reusable_key(prepared, captured, hooks=False)
        artifacts = session.authorize_fresh_image(prepared, inputs, key)

        manifest = _manifest(prepared)
        assert artifacts == (prepared.build_root / "Vtop",)
        assert manifest["reusable"] is False
        assert "lack dependency records" in manifest["reason"]
        assert not (session.slot / "current.json").exists()
        session.verify_image(prepared)


def test_pre_sim_output_in_the_generation_disables_reuse(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    session = SimulationBuildSession(_handle(tmp_path))
    with session:
        prepared, _ = _keyed_generation(tmp_path, monkeypatch, session)
        assert session.reusable_key(prepared, {}, hooks=True) is None
        assert session.reusable_key(prepared, {}, hooks=False) == "key"


@pytest.mark.parametrize(
    ("e_type", "byteorder", "loadable"),
    [(1, "little", False), (2, "little", True), (3, "little", True), (3, "big", True)],
)
def test_only_executables_and_shared_objects_get_a_dynamic_scan(
    tmp_path: Path, e_type: int, byteorder: str, loadable: bool
) -> None:
    data = 1 if byteorder == "little" else 2
    header = b"\x7fELF" + bytes([2, data]) + bytes(10) + e_type.to_bytes(2, byteorder)
    path = tmp_path / "elf"
    path.write_bytes(header + bytes(32))
    assert build_reuse._is_loadable_elf(path) is loadable
    path.write_bytes(b"#!/bin/sh\n")
    assert build_reuse._is_loadable_elf(path) is False


def test_closure_may_name_exact_toolchain_files_outside_every_root(tmp_path: Path) -> None:
    project, work, build, identity = _fresh_build(tmp_path)
    real_bin = tmp_path / "usr-local-bin" / "verilator_bin"
    real_bin.parent.mkdir()
    real_bin.write_text("real binary", encoding="utf-8")
    sibling = real_bin.with_name("unrelated")
    sibling.write_text("not hashed by the identity", encoding="utf-8")
    (build / "Vtop__ver.d").write_text(f"Vtop.cpp : {real_bin} src/top.sv\n", encoding="utf-8")
    with pytest.raises(ReadClosureError, match="outside the allowed roots"):
        collect_read_closure(build, work, identity, project, _settled_capture_ns())

    pinned = replace(identity, tool_files=frozenset({real_bin.resolve()}))
    closure = collect_read_closure(build, work, pinned, project, _settled_capture_ns())
    assert closure[f"abs:{real_bin.resolve()}"] == _sha(real_bin)
    assert verify_read_closure(closure, work, pinned, project)
    assert not verify_read_closure(
        {**closure, f"abs:{sibling.resolve()}": _sha(sibling)}, work, pinned, project
    )


@posix_only
def test_declined_key_clears_the_previous_verilator_identity(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    session = SimulationBuildSession(_handle(tmp_path))
    with session:
        prepared, inputs = _keyed_generation(tmp_path, monkeypatch, session)
        session._captured_ns[prepared.work_root] = _settled_capture_ns()
        manifest = {"read_closure": {"work:src/top.sv": inputs["src/top.sv"]}}
        assert session.reusable_key(prepared, inputs, hooks=False) == "key"
        assert session._read_closure_matches(prepared.work_root, manifest, prepared)

        assert session.reusable_key(prepared, inputs, hooks=True) is None
        assert not session._read_closure_matches(prepared.work_root, manifest, prepared)
        assert session._fresh_read_closure(prepared, "key")[0] is None


@posix_only
def test_generated_makefile_reading_unkeyed_environment_downgrades(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("BOOLEY_TEST_UNKEYED", "-DSURPRISE")
    session = SimulationBuildSession(_handle(tmp_path))
    with session:
        prepared, inputs = _keyed_generation(tmp_path, monkeypatch, session)
        (prepared.build_root / "Vtop.mk").write_text(
            "CXXFLAGS += $(BOOLEY_TEST_UNKEYED)\n", encoding="utf-8"
        )
        captured = session.capture_inputs(prepared)
        session._captured_ns[prepared.work_root] = _settled_capture_ns()
        key = session.reusable_key(prepared, captured, hooks=False)
        session.authorize_fresh_image(prepared, inputs, key)

        manifest = _manifest(prepared)
        assert manifest["reusable"] is False
        assert "BOOLEY_TEST_UNKEYED" in manifest["reason"]
        assert not (session.slot / "current.json").exists()
