"""Build a project sandbox image that bakes the repo's Python deps (ADR 0018).

The base ``booley-sandbox`` image is project-agnostic and never installs a
project's ``requirements.txt`` — and the sandbox's runtime egress is locked to
LLM endpoints, so ``pip install`` cannot run at MCP endpoint runtime. ``booley init`` bridges
this: it bakes exactly the requirements files a project lists in
``[sandbox].pip_requirements`` — nothing is auto-discovered. It drops pins on
Booley-:data:`MANAGED_PACKAGES` so a design repo can't downgrade the driver,
skips non-bakeable lines (editable/``-r``/``file:``), consolidates the rest,
generates an untracked ``.booley_project/docker/{requirements.txt,Dockerfile}``
extending ``booley-sandbox``, and builds the automatically selected
``<slug>-booley-sandbox`` image.

Notes:
  - No ``[sandbox].pip_requirements`` (or an empty list) means nothing is baked
    — the project runs the base image.
  - An explicit ``[sandbox].image`` other than the generated name means the user
    manages their own image; auto-generation is skipped.
"""

from __future__ import annotations

import hashlib
import logging
import re
import subprocess
from pathlib import Path

from booley.runtime.image_provenance import (
    LABEL_BUILD_ORIGIN,
    LABEL_PARENT_ARTIFACT,
    LABEL_PARENT_ARTIFACT_KIND,
    LABEL_RECIPE_FINGERPRINT,
    PARENT_ARTIFACT_LOCAL_IMAGE_ID,
    resolve_build_context_fingerprint,
)

logger = logging.getLogger(__name__)

BASE_IMAGE = "booley-sandbox"

# Packages the base sandbox image pins and manages (ADR 0019). A project
# requirements pin on any of these shadows the image's version at build time
# (Ibex's ``fusesoc==2.4.3`` silently downgraded the managed 2.4.6, breaking the
# driver), so such pins are dropped-and-warned rather than baked (SETUP-5).
# Both distribution names are guarded: "booley-rtl" is the PyPI name; plain
# "booley" catches stale pins written before the rename.
MANAGED_PACKAGES = frozenset({"fusesoc", "edalize", "booley", "booley-rtl"})

_GENERATED_HEADER = "# AUTO-GENERATED by `booley init` (ADR 0018)."

# Any file carrying this directive is treated as user-owned even if it still
# begins with the generated header — an explicit "hands off" for edits init's
# header-check can't otherwise see (SETUP-6).
_KEEP_DIRECTIVE = "# booley:keep"

# Trailing self-hash line write_project_image_files() stamps on generated
# files. It is how re-init tells "stale generated file" (hash matches —
# regenerate) from "hand-edited generated file" (hash mismatch — user-owned),
# closing the SETUP-6 hole where an edit that kept the header was clobbered.
_CONTENT_HASH_PREFIX = "# booley:content-hash="

_FROM_RE = re.compile(
    r"^\s*FROM(?:\s+--platform=\S+)?\s+(?P<image>[^\s]+)",
    re.IGNORECASE | re.MULTILINE,
)
_PARENT_DIRECTIVE_RE = re.compile(r"^\s*#\s*booley:parent=(?P<image>\S+)\s*$", re.MULTILINE)


class DockerImageError(RuntimeError):
    """Docker could not authoritatively inspect a Session Image."""


def _content_digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def _stamp_content_hash(body: str) -> str:
    """Append the self-hash line that lets re-init detect hand edits."""
    if body and not body.endswith("\n"):
        body += "\n"
    return f"{body}{_CONTENT_HASH_PREFIX}{_content_digest(body)}\n"


def _matches_content_hash(text: str) -> bool:
    """True when *text* is byte-for-byte what init last wrote.

    Files written before hashing carry no hash line and stay managed (the
    legacy behavior — regenerated on re-init). With a hash line present, ANY
    hand edit — even one that keeps the generated header — flips the file to
    user-owned.
    """
    lines = text.splitlines(keepends=True)
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].startswith(_CONTENT_HASH_PREFIX):
            declared = lines[i][len(_CONTENT_HASH_PREFIX) :].strip()
            rest = "".join(lines[:i] + lines[i + 1 :])
            return declared == _content_digest(rest)
    return True


def project_image_name(project_root: Path) -> str:
    """Deterministic tag for the generated project image (docker-name-safe)."""
    slug = re.sub(r"[^a-z0-9_.-]+", "-", project_root.name.lower()).strip("-._")
    return f"{slug or 'project'}-{BASE_IMAGE}"


def dockerfile_parent_image(dockerfile: Path) -> str | None:
    """Return an unambiguous direct parent, or ``None`` for a complex recipe."""
    try:
        text = dockerfile.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    directive = _PARENT_DIRECTIVE_RE.search(text)
    if directive is not None:
        return directive.group("image")
    matches = list(_FROM_RE.finditer(text))
    if len(matches) != 1:
        return None
    image = matches[0].group("image")
    if image.startswith("$"):
        return None
    return image


# ---------------------------------------------------------------------------
# Resolution
# ---------------------------------------------------------------------------


def resolve_requirements(
    project_root: Path,
    pip_requirements: list[str] | None,
) -> tuple[list[Path], list[str]]:
    """Resolve the requirements files listed in ``[sandbox].pip_requirements``.

    There is no auto-discovery: only the files a project names are baked. An
    empty or absent list bakes nothing. Returns ``(existing_paths,
    missing_entries)``; entries are repo-root-relative.
    """
    if not pip_requirements:
        return [], []
    existing: list[Path] = []
    missing: list[str] = []
    for entry in pip_requirements:
        p = project_root / entry
        if p.is_file():
            existing.append(p)
        else:
            missing.append(entry)
    return existing, missing


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def _is_bakeable(line: str) -> bool:
    """True if *line* is a PyPI/URL requirement installable from an isolated image.

    Excludes editable installs, nested -r/-c includes, and local/relative/``file:``
    path requirements (e.g. ``pkg @ file:../sub``) — those reference paths that
    don't exist in the build context and must be handled at runtime instead.
    """
    low = line.lower()
    if low.startswith(("-e ", "--editable", "-r ", "--requirement", "-c ", "--constraint")):
        return False
    if "file:" in low:
        return False
    token = line.split(maxsplit=1)[0]
    if token.startswith((".", "/")):
        return False
    if " @ " in line:
        target = line.split(" @ ", 1)[1].strip().lower()
        if target.startswith((".", "/")) or target.startswith("file:"):
            return False
    return True


def _normalize_dist(name: str) -> str:
    """PEP 503 name normalization (``cocotb_ext.AXI`` -> ``cocotb-ext-axi``)."""
    return re.sub(r"[-_.]+", "-", name.strip()).lower()


def requirement_name(line: str) -> str | None:
    """Normalized distribution name a requirement *line* installs, if it has one.

    Handles the plain ``name<spec>`` / ``name[extra]==v`` / ``name @ url`` forms.
    Option lines (``-r``/``-e``) and bare URL/VCS installs carry no normalizable
    name here and return ``None``.
    """
    if line.startswith("-") or "://" in line.split(" @ ", 1)[0]:
        return None
    head = line.split(" @ ", 1)[0].strip()
    name = re.split(r"[\[<>=!~;, ]", head, maxsplit=1)[0].strip()
    return _normalize_dist(name) or None


def _managed_package(line: str) -> str | None:
    """Normalized name if *line* pins a Booley-:data:`MANAGED_PACKAGES` package."""
    norm = requirement_name(line)
    return norm if norm in MANAGED_PACKAGES else None


def base_image_packages(image: str = BASE_IMAGE, *, timeout_s: int = 60) -> dict[str, str]:
    """``{normalized dist name: version}`` installed in *image*.

    Returns ``{}`` when the image can't be queried at all (docker missing, image
    not built, pip absent). Every caller treats that as "nothing known about the
    base", so the query failing is never fatal — it only costs the advisory it
    would have produced.
    """
    try:
        result = subprocess.run(
            [
                "docker",
                "run",
                "--rm",
                "--entrypoint",
                "python3",
                image,
                "-m",
                "pip",
                "list",
                "--format=freeze",
                "--disable-pip-version-check",
            ],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            check=False,
        )
    except (subprocess.SubprocessError, OSError):
        logger.debug("could not query packages in base image %s", image, exc_info=True)
        return {}
    if result.returncode != 0:
        logger.debug("pip list in %s exited %s", image, result.returncode)
        return {}
    versions: dict[str, str] = {}
    for line in result.stdout.splitlines():
        name, sep, version = line.strip().partition("==")
        if sep and name.strip() and version.strip():
            versions[_normalize_dist(name)] = version.strip()
    return versions


#: Requirement text after the distribution name and optional extras — the
#: version specifier, if the line carries one.
_REQ_SPEC_RE = re.compile(r"^[A-Za-z0-9._-]+(?:\[[^\]]*\])?\s*(?P<spec>.*)$")


def curated_overrides(
    requirements: list[str],
    base_versions: dict[str, str],
) -> list[tuple[str, str, str]]:
    """``(requirement, dist name, base version)`` for pins that re-version the base.

    A project owns its sim stack, so these pins are honored — but they replace a
    version the base sandbox image curated (and validated, in cocotb's case)
    with no trace in the build output, which is how a ``cocotb 2.0.1 -> 1.5.1``
    downgrade rides in unannounced (F-13).

    Only lines that can actually move the installed version qualify: a bare name
    leaves an already-satisfied install alone, and an ``==`` pin equal to what
    the base already has is a no-op. Any other specifier is reported, since
    evaluating a range against a version needs a resolver we don't have here.
    """
    overrides: list[tuple[str, str, str]] = []
    for line in requirements:
        name = requirement_name(line)
        if name is None or name not in base_versions:
            continue
        match = _REQ_SPEC_RE.match(line.split(";", 1)[0].split(" @ ", 1)[0].strip())
        spec = match.group("spec").strip() if match else ""
        if not spec:
            continue
        exact = re.fullmatch(r"==\s*([^\s,]+)", spec)
        if exact and exact.group(1) == base_versions[name]:
            continue
        overrides.append((line, name, base_versions[name]))
    return overrides


def consolidated_requirements(
    project_root: Path,
    req_files: list[Path],
) -> tuple[str, list[str], list[str], list[str]]:
    """Merge *req_files* into one requirements body, deduped, with provenance.

    First occurrence of each requirement line wins; later duplicates are dropped.
    Conflicting version pins are left intact so ``pip`` surfaces the conflict.
    Non-bakeable lines (editable/local/file/nested-include) are dropped, as are
    pins on Booley-managed packages (:data:`MANAGED_PACKAGES`) that would shadow
    the base image's version (SETUP-5).

    Returns ``(body, kept, skipped, dropped_managed)`` — the requirement strings
    included, excluded as non-bakeable, and dropped as managed-package pins.
    """
    sources = ", ".join(p.relative_to(project_root).as_posix() for p in req_files)
    lines = [_GENERATED_HEADER, f"# Sources: {sources}", ""]
    seen: set[str] = set()
    kept: list[str] = []
    skipped: list[str] = []
    dropped_managed: list[str] = []
    for f in req_files:
        rel = f.relative_to(project_root).as_posix()
        added = False
        for raw in f.read_text(encoding="utf-8").splitlines():
            stripped = raw.strip()
            if not stripped or stripped.startswith("#") or stripped in seen:
                continue
            seen.add(stripped)
            if not _is_bakeable(stripped):
                skipped.append(stripped)
                continue
            if _managed_package(stripped) is not None:
                dropped_managed.append(stripped)
                continue
            if not added:
                lines.append(f"# from {rel}")
                added = True
            kept.append(stripped)
            lines.append(stripped)
        if added:
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n", kept, skipped, dropped_managed


def _dockerfile_body() -> str:
    # Install as root into SYSTEM site-packages, not the agent's ~/.local — the
    # base image's booley-pip-local named volume shadows /home/agent/.local at
    # runtime (see data/docker/Dockerfile), which would hide a --user install.
    return (
        f"{_GENERATED_HEADER}\n"
        "# Extends the base sandbox with this project's Python deps. Set\n"
        "# [sandbox].image to your own image to take over and stop regeneration.\n"
        f"FROM {BASE_IMAGE}\n"
        "USER root\n"
        "COPY requirements.txt /tmp/booley-project-requirements.txt\n"
        "RUN pip install --no-cache-dir --break-system-packages "
        "-r /tmp/booley-project-requirements.txt\n"
        "USER agent\n"
    )


def is_managed_generated_file(path: Path) -> bool:
    """True if *path* is init's to (re)generate — absent, or a prior auto-file untouched.

    A file that is missing (never generated), or that still begins with
    :data:`_GENERATED_HEADER`, carries no :data:`_KEEP_DIRECTIVE`, and matches
    its stamped self-hash is managed and safe to overwrite. Anything else — a
    hand-written Dockerfile, an edited generated one (hash mismatch), or one
    flagged ``# booley:keep`` — is user-owned; init must not clobber it
    (SETUP-6). Unreadable files are treated as user-owned.
    """
    if not path.exists():
        return True
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    if _KEEP_DIRECTIVE in text:
        return False
    if not text.lstrip().startswith(_GENERATED_HEADER):
        return False
    return _matches_content_hash(text)


def write_managed_dockerfile(docker_dir: Path) -> Path:
    """Write (only) the generated ``Dockerfile`` into *docker_dir*, self-hashed.

    Split out of :func:`write_project_image_files` for the hand-authored
    requirements flow (F-5): when the user supplies ``requirements.txt``
    themselves and no Dockerfile exists, init contributes just the standard
    Dockerfile that bakes it, leaving the user's file untouched.
    """
    docker_dir.mkdir(parents=True, exist_ok=True)
    dockerfile = docker_dir / "Dockerfile"
    dockerfile_body, _requirements_body = managed_project_image_files("")
    dockerfile.write_text(dockerfile_body, encoding="utf-8")
    return dockerfile


def managed_project_image_files(requirements_body: str) -> tuple[str, str]:
    """Return the exact managed Dockerfile and requirements-file contents."""
    return (
        _stamp_content_hash(_dockerfile_body()),
        _stamp_content_hash(requirements_body),
    )


def write_project_image_files(
    docker_dir: Path,
    requirements_body: str,
) -> tuple[Path, Path]:
    """Write the generated ``requirements.txt`` + ``Dockerfile`` into *docker_dir*.

    Both files get a trailing self-hash line so a later ``booley init`` can
    tell an untouched generated file (regenerate) from a hand-edited one
    (user-owned, SETUP-6) — see :func:`is_managed_generated_file`.
    """
    docker_dir.mkdir(parents=True, exist_ok=True)
    dockerfile_body, requirements_content = managed_project_image_files(requirements_body)
    dockerfile = docker_dir / "Dockerfile"
    requirements = docker_dir / "requirements.txt"
    dockerfile.write_text(dockerfile_body, encoding="utf-8")
    requirements.write_text(requirements_content, encoding="utf-8")
    return dockerfile, requirements


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------


def build_project_image(image: str, docker_dir: Path, *, verbose: bool = False) -> bool:
    """``docker build`` the generated image. Context is *docker_dir* (small, no
    repo .dockerignore interference). Returns success."""
    dockerfile = docker_dir / "Dockerfile"
    if not dockerfile.is_file():
        logger.error("project image Dockerfile not found at %s", dockerfile)
        return False
    labels = [
        "--label",
        f"{LABEL_RECIPE_FINGERPRINT}={resolve_build_context_fingerprint(docker_dir)}",
        "--label",
        f"{LABEL_BUILD_ORIGIN}=local",
    ]
    parent = dockerfile_parent_image(dockerfile)
    try:
        parent_id = docker_image_id(parent) if parent else None
    except DockerImageError as exc:
        logger.error("project image parent inspection failed: %s", exc)
        return False
    if parent_id:
        labels += [
            "--label",
            f"{LABEL_PARENT_ARTIFACT_KIND}={PARENT_ARTIFACT_LOCAL_IMAGE_ID}",
            "--label",
            f"{LABEL_PARENT_ARTIFACT}={parent_id}",
        ]
    cmd = ["docker", "build", "-t", image, *labels, "-f", str(dockerfile), str(docker_dir)]
    try:
        result = subprocess.run(
            cmd,
            capture_output=not verbose,
            text=True,
            timeout=1800,
            check=False,
        )
    except (FileNotFoundError, subprocess.SubprocessError) as exc:
        logger.error("project image build failed: %s", exc)
        return False
    if result.returncode != 0:
        detail = (getattr(result, "stderr", "") or "").strip()
        logger.error("project image build failed (rc=%s): %s", result.returncode, detail[-500:])
        return False
    return True


def docker_image_id(image: str) -> str | None:
    """Resolve a local Docker artifact; return ``None`` only when it is absent."""
    try:
        result = subprocess.run(
            ["docker", "image", "inspect", image, "--format", "{{.Id}}"],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except (FileNotFoundError, subprocess.SubprocessError) as exc:
        raise DockerImageError(f"could not inspect Docker image {image!r}: {exc}") from exc
    value = result.stdout.strip()
    if result.returncode == 0:
        if value:
            return value
        raise DockerImageError(f"Docker returned no immutable ID for image {image!r}")
    detail = (result.stderr or result.stdout).strip()
    if "no such image" in detail.lower():
        return None
    raise DockerImageError(
        f"could not inspect Docker image {image!r}: {detail or f'Docker exited {result.returncode}'}"
    )
