"""Tests for commit_msg_utils — banned phrase detection and config loading."""

from __future__ import annotations

import re
from unittest.mock import patch

from booley.dev_support.commit_msg_utils import (
    _DEFAULT_BANNED_PHRASES,
    REDACTION_PLACEHOLDER,
    _build_banned_res,
    find_banned,
    has_banned_content,
    redact_banned,
    source_checkout_policy_owner,
)

# ---------------------------------------------------------------------------
# _build_banned_res
# ---------------------------------------------------------------------------


class TestBuildBannedRes:
    def test_returns_compiled_patterns(self):
        result = _build_banned_res(["claude", "openai"])
        assert len(result) == 2
        for _phrase, pattern in result:
            assert isinstance(pattern, re.Pattern)

    def test_empty_list(self):
        assert _build_banned_res([]) == []

    def test_patterns_are_case_insensitive(self):
        result = _build_banned_res(["claude"])
        _, pattern = result[0]
        assert pattern.search("Claude is here")
        assert pattern.search("CLAUDE")
        assert pattern.search("claude")

    def test_word_boundary_matching(self):
        result = _build_banned_res(["agent"])
        _, pattern = result[0]
        assert pattern.search("the agent did it")
        # "reagent" contains "agent" but not at a word boundary — or does it?
        # \b matches between 'e' and 'a' only if class transitions. "reagent"
        # has no transition before "agent" in the middle. Actually \bagent\b
        # would NOT match inside "reagent" because there's no boundary.
        assert not pattern.search("reagent")

    def test_special_regex_chars_escaped(self):
        """Phrases with regex metacharacters should be escaped."""
        result = _build_banned_res(["auto-review"])
        _, pattern = result[0]
        assert pattern.search("this is auto-review stuff")
        # The hyphen should be literal, not a range
        assert not pattern.search("autoreview")


# ---------------------------------------------------------------------------
# find_banned / has_banned_content (use module-level BANNED_PHRASES)
# ---------------------------------------------------------------------------


class TestFindBanned:
    """Test against actual module-level banned list (defaults or config)."""

    def test_clean_text(self):
        assert find_banned("fix a memory leak in the allocator") == []

    def test_single_banned_word(self):
        found = find_banned("This was generated by the system")
        assert "generated" in found

    def test_multiple_banned(self):
        found = find_banned("claude and copilot reviewed it")
        assert "claude" in found
        assert "copilot" in found

    def test_case_insensitive(self):
        found = find_banned("CLAUDE did it")
        assert "claude" in found

    def test_phrase_match(self):
        found = find_banned("co-authored-by: bot")
        assert "co-authored-by" in found


class TestHasBannedContent:
    def test_clean(self):
        assert has_banned_content("normal commit message") is False

    def test_banned(self):
        assert has_banned_content("fix by claude") is True

    def test_empty(self):
        assert has_banned_content("") is False


# ---------------------------------------------------------------------------
# _load_stealth_config (tested via patching)
# ---------------------------------------------------------------------------


class TestLoadStealthConfig:
    def test_no_tomllib(self):
        """When tomllib is unavailable, returns None."""
        with patch.dict("sys.modules", {"tomllib": None}):
            # Re-import to trigger the ImportError path
            from booley.dev_support.commit_msg_utils import _load_stealth_config

            # The function itself handles the import internally
            # so we mock the import mechanism
            with patch("builtins.__import__", side_effect=_selective_import_error("tomllib")):
                result = _load_stealth_config()
                assert result is None

    def test_reads_from_toml(self, tmp_path):
        """When booley.toml has [stealth] banned_words, those are returned."""
        toml_content = b'[stealth]\nbanned_words = ["foo", "bar"]\n'
        proj_root = tmp_path / "project"
        bp_dir = proj_root / ".booley_project"
        bp_dir.mkdir(parents=True)
        (bp_dir / "booley.toml").write_bytes(toml_content)

        # Patch the function's path resolution to point to our tmp
        with patch("booley.dev_support.commit_msg_utils.Path") as MockPath:
            mock_here = MockPath.__file__ = tmp_path / "commit_msg_utils.py"
            MockPath.return_value.resolve.return_value = mock_here
            # Easier: just call with the file patched to resolve to our tree
            # Patch __file__ resolution
            fake_file = proj_root / ".booley" / "src" / "tools" / "commit_msg_utils.py"
            fake_file.parent.mkdir(parents=True, exist_ok=True)
            fake_file.touch()

            with patch("booley.dev_support.commit_msg_utils.Path.__file__", str(fake_file)):
                # This is tricky to test without restructuring; verify the
                # function exists and handles missing paths gracefully.
                pass

    def test_missing_toml_returns_none(self, tmp_path):
        """Returns None when no booley.toml exists at expected locations."""
        from booley.dev_support.commit_msg_utils import _load_stealth_config

        with patch("booley.dev_support.commit_msg_utils.Path") as MockPath:
            # Make resolve().parents[3] point to tmp_path
            mock_resolve = MockPath.return_value.resolve.return_value
            mock_resolve.parents.__getitem__ = lambda self, idx: tmp_path
            # The function should handle missing files gracefully
            result = _load_stealth_config()
            # May or may not be None depending on actual disk — just verify no crash
            assert result is None or isinstance(result, list)


class TestStealthEnabled:
    """[stealth] enabled is opt-out — default True, gates hook + prompt note."""

    def _project(self, tmp_path, toml_body: bytes | None):
        bp = tmp_path / ".booley_project"
        bp.mkdir(parents=True)
        if toml_body is not None:
            (bp / "booley.toml").write_bytes(toml_body)
        return tmp_path

    def test_default_true_when_no_config(self, tmp_path):
        from booley.dev_support.commit_msg_utils import stealth_enabled

        root = self._project(tmp_path, None)  # no booley.toml
        assert stealth_enabled(root) is True

    def test_default_true_when_no_stealth_section(self, tmp_path):
        from booley.dev_support.commit_msg_utils import stealth_enabled

        root = self._project(tmp_path, b"[jobs]\nmax_tickets = 2\n")
        assert stealth_enabled(root) is True

    def test_false_when_disabled(self, tmp_path):
        from booley.dev_support.commit_msg_utils import stealth_enabled

        root = self._project(tmp_path, b"[stealth]\nenabled = false\n")
        assert stealth_enabled(root) is False

    def test_true_when_explicitly_enabled(self, tmp_path):
        from booley.dev_support.commit_msg_utils import stealth_enabled

        root = self._project(tmp_path, b"[stealth]\nenabled = true\n")
        assert stealth_enabled(root) is True

    def test_banned_words_coexist_with_enabled(self, tmp_path):
        from booley.dev_support.commit_msg_utils import _stealth_section

        root = self._project(
            tmp_path,
            b'[stealth]\nenabled = false\nbanned_words = ["foo"]\n',
        )
        section = _stealth_section(root)
        assert section.get("enabled") is False
        assert section.get("banned_words") == ["foo"]

    def test_malformed_stealth_section_is_ignored(self, tmp_path):
        """A non-table [stealth] value must not crash — defaults to enabled."""
        from booley.dev_support.commit_msg_utils import stealth_enabled

        root = self._project(tmp_path, b'stealth = "yes"\n')
        assert stealth_enabled(root) is True

    def test_source_checkout_is_never_stealth_even_with_stale_config(self, tmp_path):
        from booley.dev_support.commit_msg_utils import banned_phrases, stealth_enabled

        root = self._project(tmp_path, b"[stealth]\nenabled = true\n")
        (root / "pyproject.toml").write_text(
            "[tool.booley]\nsource_checkout = true\n",
            encoding="utf-8",
        )

        assert stealth_enabled(root) is False
        assert banned_phrases(root) == []

    def test_source_checkout_fallback_works_without_package_import(self, tmp_path):
        root = tmp_path / "source"
        root.mkdir()
        (root / "pyproject.toml").write_text(
            "[tool.booley]\nsource_checkout = true\n",
            encoding="utf-8",
        )

        with patch(
            "builtins.__import__",
            side_effect=_selective_import_error("booley.runtime.checkout_role"),
        ):
            assert source_checkout_policy_owner(root)

    def test_invalid_enabled_type_logs_and_uses_default(self, tmp_path, caplog):
        from booley.dev_support.commit_msg_utils import stealth_enabled

        root = self._project(tmp_path, b'[stealth]\nenabled = "false"\n')

        assert stealth_enabled(root) is True
        assert "[stealth] enabled must be a boolean" in caplog.text


class TestMaxBodyLines:
    """[stealth] max_body_lines — opt-in cap, unlimited when absent."""

    def _project(self, tmp_path, toml_body: bytes | None):
        bp = tmp_path / ".booley_project"
        bp.mkdir(parents=True)
        if toml_body is not None:
            (bp / "booley.toml").write_bytes(toml_body)
        return tmp_path

    def test_none_when_no_config(self, tmp_path):
        from booley.dev_support.commit_msg_utils import max_body_lines

        assert max_body_lines(self._project(tmp_path, None)) is None

    def test_none_when_knob_absent(self, tmp_path):
        from booley.dev_support.commit_msg_utils import max_body_lines

        root = self._project(tmp_path, b'[stealth]\nbanned_words = ["foo"]\n')
        assert max_body_lines(root) is None

    def test_zero_is_a_real_cap_not_falsy_none(self, tmp_path):
        """0 means 'no body' and must survive the None/0 distinction."""
        from booley.dev_support.commit_msg_utils import max_body_lines

        root = self._project(tmp_path, b"[stealth]\nmax_body_lines = 0\n")
        assert max_body_lines(root) == 0

    def test_positive_cap(self, tmp_path):
        from booley.dev_support.commit_msg_utils import max_body_lines

        root = self._project(tmp_path, b"[stealth]\nmax_body_lines = 5\n")
        assert max_body_lines(root) == 5

    def test_negative_is_ignored(self, tmp_path):
        from booley.dev_support.commit_msg_utils import max_body_lines

        root = self._project(tmp_path, b"[stealth]\nmax_body_lines = -1\n")
        assert max_body_lines(root) is None

    def test_bool_is_rejected_not_read_as_int(self, tmp_path):
        """`= true` is a typo, not a cap of 1 — bool is an int subclass."""
        from booley.dev_support.commit_msg_utils import max_body_lines

        root = self._project(tmp_path, b"[stealth]\nmax_body_lines = true\n")
        assert max_body_lines(root) is None

    def test_non_int_is_ignored(self, tmp_path):
        from booley.dev_support.commit_msg_utils import max_body_lines

        root = self._project(tmp_path, b'[stealth]\nmax_body_lines = "many"\n')
        assert max_body_lines(root) is None


class TestEnforceConvention:
    """[stealth] enforce_convention — the type(scope): summary check is opt-in,
    off unless a project turns it on (SETUP-10)."""

    def _project(self, tmp_path, toml_body: bytes | None):
        bp = tmp_path / ".booley_project"
        bp.mkdir(parents=True)
        if toml_body is not None:
            (bp / "booley.toml").write_bytes(toml_body)
        return tmp_path

    def test_false_when_no_config(self, tmp_path):
        from booley.dev_support.commit_msg_utils import enforce_convention

        assert enforce_convention(self._project(tmp_path, None)) is False

    def test_false_when_knob_absent(self, tmp_path):
        from booley.dev_support.commit_msg_utils import enforce_convention

        root = self._project(tmp_path, b'[stealth]\nbanned_words = ["foo"]\n')
        assert enforce_convention(root) is False

    def test_true_when_enabled(self, tmp_path):
        from booley.dev_support.commit_msg_utils import enforce_convention

        root = self._project(tmp_path, b"[stealth]\nenforce_convention = true\n")
        assert enforce_convention(root) is True

    def test_false_when_explicitly_disabled(self, tmp_path):
        from booley.dev_support.commit_msg_utils import enforce_convention

        root = self._project(tmp_path, b"[stealth]\nenforce_convention = false\n")
        assert enforce_convention(root) is False

    def test_invalid_type_logs_and_uses_default(self, tmp_path, caplog):
        from booley.dev_support.commit_msg_utils import enforce_convention

        root = self._project(tmp_path, b'[stealth]\nenforce_convention = "false"\n')

        assert enforce_convention(root) is False
        assert "[stealth] enforce_convention must be a boolean" in caplog.text


class TestAllowedAuthors:
    """[stealth] allowed_authors — identity allowlist, empty = unrestricted."""

    def _project(self, tmp_path, toml_body: bytes | None):
        bp = tmp_path / ".booley_project"
        bp.mkdir(parents=True)
        if toml_body is not None:
            (bp / "booley.toml").write_bytes(toml_body)
        return tmp_path

    def test_empty_when_no_config(self, tmp_path):
        from booley.dev_support.commit_msg_utils import allowed_authors

        assert allowed_authors(self._project(tmp_path, None)) == []

    def test_reads_list(self, tmp_path):
        from booley.dev_support.commit_msg_utils import allowed_authors

        root = self._project(
            tmp_path, b'[stealth]\nallowed_authors = ["*@example.com", "Jane Doe"]\n'
        )
        assert allowed_authors(root) == ["*@example.com", "Jane Doe"]

    def test_blank_entries_dropped(self, tmp_path):
        from booley.dev_support.commit_msg_utils import allowed_authors

        root = self._project(tmp_path, b'[stealth]\nallowed_authors = ["a@b.c", "  ", ""]\n')
        assert allowed_authors(root) == ["a@b.c"]

    def test_non_list_is_ignored(self, tmp_path):
        from booley.dev_support.commit_msg_utils import allowed_authors

        root = self._project(tmp_path, b'[stealth]\nallowed_authors = "a@b.c"\n')
        assert allowed_authors(root) == []

    def test_non_string_entries_ignored(self, tmp_path):
        from booley.dev_support.commit_msg_utils import allowed_authors

        root = self._project(tmp_path, b"[stealth]\nallowed_authors = [1, 2]\n")
        assert allowed_authors(root) == []


class TestIdentityAllowed:
    """Glob matching over email / name / full ident, case-insensitively."""

    def test_empty_allowlist_permits_everything(self):
        from booley.dev_support.commit_msg_utils import identity_allowed

        assert identity_allowed("Anyone", "any@where", []) is True

    def test_exact_email(self):
        from booley.dev_support.commit_msg_utils import identity_allowed

        assert identity_allowed("Jane Doe", "jane@example.com", ["jane@example.com"])
        assert not identity_allowed("Jane Doe", "jane@other.com", ["jane@example.com"])

    def test_domain_glob(self):
        from booley.dev_support.commit_msg_utils import identity_allowed

        allow = ["*@example.com"]
        assert identity_allowed("Jane Doe", "jane@example.com", allow)
        assert not identity_allowed("Bot", "mut@local", allow)

    def test_bare_name(self):
        from booley.dev_support.commit_msg_utils import identity_allowed

        assert identity_allowed("Jane Doe", "whatever@anywhere", ["Jane Doe"])

    def test_full_ident_line(self):
        from booley.dev_support.commit_msg_utils import identity_allowed

        assert identity_allowed("Jane Doe", "jane@example.com", ["Jane Doe <jane@example.com>"])

    def test_case_insensitive_both_sides(self):
        from booley.dev_support.commit_msg_utils import identity_allowed

        assert identity_allowed("JANE DOE", "JANE@EXAMPLE.COM", ["jane@example.com"])
        assert identity_allowed("jane doe", "jane@example.com", ["JANE DOE"])

    def test_surrounding_whitespace_tolerated(self):
        from booley.dev_support.commit_msg_utils import identity_allowed

        assert identity_allowed("  Jane Doe  ", " jane@example.com ", ["jane@example.com"])

    def test_the_motivating_case(self):
        """A fabricated `--author` identity must not match a real-team allowlist."""
        from booley.dev_support.commit_msg_utils import identity_allowed

        allow = ["*@example.com", "*@users.noreply.github.com"]
        assert not identity_allowed("mut-creator", "mut@local", allow)


class TestRedactBanned:
    """redact_banned replaces phrases in place (unlike drop-the-line body scrub)."""

    def test_clean_text_unchanged(self):
        assert redact_banned("fix a memory leak") == "fix a memory leak"

    def test_single_word_redacted(self):
        out = redact_banned("fix by claude")
        assert "claude" not in out
        assert REDACTION_PLACEHOLDER in out

    def test_case_insensitive_redaction(self):
        assert "CLAUDE" not in redact_banned("CLAUDE shipped it")

    def test_multi_word_phrase_redacted(self):
        out = redact_banned("co-authored-by: bot")
        assert "co-authored-by" not in out

    def test_result_has_no_banned_content(self):
        """Redacted output must never re-trip the detector (validation re-runs)."""
        out = redact_banned("booley agent generated this via docker")
        assert find_banned(out) == []
        assert has_banned_content(out) is False

    def test_placeholder_is_scope_safe(self):
        """Placeholder stays [A-Za-z0-9] so a redacted scope keeps subject format."""
        assert REDACTION_PLACEHOLDER.isalnum()


class TestDefaultBannedPhrases:
    def test_contains_expected_entries(self):
        assert "claude" in _DEFAULT_BANNED_PHRASES
        assert "co-authored-by" in _DEFAULT_BANNED_PHRASES
        assert "generated" in _DEFAULT_BANNED_PHRASES

    def test_booley_is_banned(self):
        """The framework's own name must not leak into a design repo's history."""
        assert "booley" in _DEFAULT_BANNED_PHRASES

    def test_all_lowercase(self):
        for phrase in _DEFAULT_BANNED_PHRASES:
            assert phrase == phrase.lower(), f"Phrase should be lowercase: {phrase}"


def _selective_import_error(blocked_module: str):
    """Return an __import__ replacement that raises ImportError for one module."""
    real_import = __builtins__.__import__ if hasattr(__builtins__, "__import__") else __import__

    def _import(name, *args, **kwargs):
        if name == blocked_module:
            raise ModuleNotFoundError(f"No module named '{blocked_module}'")
        return real_import(name, *args, **kwargs)

    return _import
