# project false paths
set_false_path -from [get_ports {rst_ni}]


# Auto-generated by Booley simple Yosys/OpenSTA backend.
create_clock -name clk_i -period 4.000000 [get_ports {clk_i}]
if { [catch { set input_ports [remove_from_collection [all_inputs] [get_ports {clk_i}]] }] } { set input_ports [all_inputs] }
set_input_delay -clock clk_i 1.200000 $input_ports
set_output_delay -clock clk_i 2.800000 [all_outputs]
catch { set_driving_cell -lib_cell BUF_X1 $input_ports }
catch { set_load 10.0 [all_outputs] }
