create_clock -name clk_i -period 25.000000 [get_ports {clk_i}]
set_input_delay -clock clk_i 0.0 [all_inputs]
set_output_delay -clock clk_i 0.0 [all_outputs]
set_false_path -from [get_ports {mode_i}]


# Auto-generated by Booley simple Yosys/OpenSTA backend.
