#Auto generated by Edalize

all: lint

lint: rtl/top.sv rtl/legacy.v lint/rules.cfg lint/waivers.txt lint/waivers_extra.txt
	$(EDALIZE_LAUNCHER) verible-verilog-lint --parse_fatal --lint_fatal=false --rules=-module-filename,line-length --ruleset=default --show_diagnostic_context --rules_config=lint/rules.cfg --waiver_files=lint/waivers.txt,lint/waivers_extra.txt rtl/top.sv rtl/legacy.v
